base_url = "https://bryantconquest.com"
compile_sass = true
title = "Hera theme"
description = "A clean blogging theme"

highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
hera_sticky = true
hera_reverse = false
hera_links = [
    {url = "https://google.com", name = "About"},
]
