base_url = "https://bryantconquest.com"
compile_sass = true
title = "Hera theme"
description = "A clean blogging theme"

[extra]
hera_sticky = true
hera_reverse = false
hera_theme = "theme-base-10"
hera_links = [
    {url = "https://google.com", name = "About"},
]
