name = "hera"
description = "Simple blog theme with bright colors"
license = "MIT"
homepage = "https://github.com/BConquest/zola-hera"
min_version = "0.1.0"
demo = "https://bryantconquest.com"

[extra]
hera_sticky = true
hera_reverse = false
hera_links = [
]

[author]
name = "Bryant Conquest"
homepage = "https://bryantconquest.com"
